Autotools overhaul
Genivia/ugrep pull request #370
Opened 2024-03-11 23:29 UTC by drok

Autotools usage is brought to 'textbook' standards, following closely the usage recommended by the autoconf/automake Fine Manuals.

## Refactorings

There are many refactorings, some of which could be standalone, but the entire package is more than the sum of its parts. The big picture:
  - `make distcheck` passes - ie, a valid, complete tarball source distribution is produced
  - cross compilation works out-of-the-box
  - binaries are portable to any CPU matching the target architecture (fixes Genivia/ugrep#368)
    - an x86_64 binary runs on **all** x86_64 CPUs, SIMD capability is used when present
    - ARMv6 binaries run on all ARMv6+ CPUs (w/o NEON, as FPU is not supported on this architecture)
    - ARMv7 binaries run on all ARMv7+ CPUs, (w/NEON where CPU supports it)
    - ARMv8 binaries run all all ARMv8+ CPUs (NEON enabled everywhere, as it is required by ARMv8 spec)

## Careful review needed

  - I touched pattern.cpp in https://github.com/Mergesium/ugrep/commit/201c50840ab4d65cfbd36d2587748cccc1cce2c6#diff-2ba845febcd8c704ca432f4156d394908201b6d2721b177a71d81e3cbc57cfddL457-L471 - I'm not sure I preserved the intended conditional improved Boyer-Moore parameter calculation.
  - Testing on ARM targets not done because
    - I don't have a sysroot setup to fully cross-compile for ARM at this time

## Suggested further work

The matcher.cpp file should be split into architecture-dependent compilation units.
  - syntax highlighting this file in capable editors is all but impossible because it contains interleaved active and inactive code paths, so there is not a single view which would be accurate.
  - the COMPILE_{AVX2, ...} should not be pre-processor defines at all.
The test suite is split into two Parallel Harness tests (single thread and multi-thread), which can run in parallel, but it should be further split up into granular tests (ie, each pass/fail corresponds to one feature tested).
  - This would allow any pass/fail to be easier to decipher
  - Would allow targeted debugging where necessary. Eg. the Autotools Integration for VScode is able to configure the debugger for individual tests automatically, so any test failure can be debugged with one click. This obviously cannot work if there are no individual tests.

The ugrep.exe binary should be removed from the repo. This binary can be built on Linux using cross-compilation. The pcre2 library supports cross-compilation out of the box.

## References

  - Mergesium [Knowledge Base entry for ugrep](https://autotools.mergesium.com/kb/ugrep)
    - documents the issues one would encounter when integrating ugrep into other work, and workarounds.

I have found many of the the problems here using the Autotools Integration for VSCode (an extension I wrote), which was instrumental in making this depth of change easy and predictable.

This work completes what I intended to do for Genivia/ugrep#339

2024-03-12 02:38 UTC, genivia-inc requested changes
Instead of [5.0.0] I prefer to use the major and minor version only, which means less manual updating to do.

Instead of `PACKAGE_VERSION`, I have to use the "5.1.1" string because I'm also building on MSVC++ without autotools.

2024-03-12 02:44 UTC, genivia-inc reviewed
In configure.ac, why change `AX_CXX_COMPILE_STDCXX([11], [ext], [optional])` from `mandatory` to `optional` when C++11 is used in the code base? https://www.gnu.org/software/autoconf-archive/ax_cxx_compile_stdcxx.html

2024-03-12 02:48 UTC, genivia-inc commented on patterns/Makefile.am
Having a makefile for patterns does not make sense IMHO. It complicates maintenance, having to keep this file in sync with files added to or removed from the patterns subdirs. I prefer not to use this approach and stick to the current datadir install in the install-data-hook.

2024-03-12 03:06 UTC, genivia-inc commented on completions/fish/compgen
In principle it is nice to generate fish and zsh completions automatically from the compen scripts that I wrote to save my time having to write completions by hand. But I did not want to create a makefile to do this automatically every time ugrep is installed, because running compgen is practically never needed, unless in the rare case that an option is added or changed to ugrep and then I can run it on my end up front. Running the scripts is not going to happen with each release, only rarely. I wonder if this doesn't add unnecessary overhead to install or make things more dependent on tools e.g. sed with different versions (GNU/BSD) of sed. I added the compgen script to the distro in case someone wants to use it and for releasing all relevant scripts with the distro.

2024-03-12 03:35 UTC, drok commented
> In configure.ac, why change `AX_CXX_COMPILE_STDCXX([11], [ext], [optional])` from `mandatory` to `optional` when C++11 is used in the code base? https://www.gnu.org/software/autoconf-archive/ax_cxx_compile_stdcxx.html

This is a cut-and-paste error - my bad. Fixed in 6efd623

2024-03-12 03:46 UTC, drok commented on completions/fish/compgen
If you're not confident in the portability of the sed scripts in `compgen`, is distributing the generated files a solution?

I think including the recipe to generate completions is the right thing to do, and the installation time is exactly the right time for them to be generated, because at least in theory, they should reflect the installed program's cmd line options, as configured. Then someone could customize their copy of the program and have a way to update their corresponding completions without doing more manual work than necessary.

I would say the real issue is that the options exposed in the completions are out of sync with the options supported by the program, and that __is__ a problem. Eg, if you compile compression libs, then the '-z' option should not appear in the completions, and the same for other configurable options, like color, etc.

The fact that nearly identical completions are generated at each release is not a problem, just as generating nearly identical machine code is not a problem. It allows change, improvement, no matter how small, to be reliably released to the end user. Releasing with outdated completions would be a more serious (perhaps embarrassing if not disastrous) problem, no?

2024-03-12 04:31 UTC, drok commented on patterns/Makefile.am
The problem is that the install-data-hook was broken. It caused distcheck to fail.

Distributing a lot of files with automake is a solved problem: https://stackoverflow.com/a/6397144/7859025

I whole-heartedly recommend running [`make distcheck`](https://www.gnu.org/software/automake/manual/html_node/Checking-the-Distribution.html) to check your project.

2024-03-12 04:47 UTC, drok commented on completions/fish/compgen
An elegant way to generate completions is to have a "tool" binary program, compiled from the same sources, but which calls a `output_completions()` C function, which dumps out the `--help` text but in 'completion' format - no sed scripts necessary. It would help to generate `--help` more programmatically.

This tool would be listed as `noinst_PROGRAMS` since it would not be installed, then have a custom target like the following to output it whenever the sources change:

```
noinst_PROGAMS = ug.completions.tool
ug_completions_tool_SOURCES = completions.cpp help.cpp

ug.fish.completions : ug.completions.tool
  ./$< --fish -o $@

ug.zsh.completions : ug.completions.tool
  ./$< --zsh -o $@
```

2024-03-12 05:10 UTC, drok commented
> Instead of [5.0.0] in configure.ac, I prefer to use the major and minor version only, which means less manual updating to do.
> 
> Instead of `PACKAGE_VERSION` in ugrep.hpp, I have to use the "5.1.1" string because I'm also building on MSVC++ without autotools.

So you __want__ the version string in configure.ac to be different than that in visual studio? You don't care that the version number that source users see is different than the binary users?

Note the Parallel Harness commit, after which the test result headers include the version number from AC_INIT. See [here](https://github.com/Mergesium/ugrep/actions/runs/8238386083/job/22529214262#step:5:392) for an example, or run `make check`

The version number is also used to determine the tarball filename, the version number in the header of the manpage, and the version number someone sees when they open your project in VSCode with my Autotools Integration extension - surely you don't want that number to be wrong?

![image](https://github.com/Genivia/ugrep/assets/830318/f331f1f8-0171-426b-893f-a271320aa86b)

You can have configure generate a version resource to use in visual studio like described here https://stackoverflow.com/questions/23204774/how-do-you-set-the-version-of-a-c-cli-project-in-visual-studio

Or the other way around, have visual studio generate configure.ac from a template, inserting the project version number.

In any case, consistent versioning of your project is needed; I don't think setting the version number in a source file like `ugrep.hpp` is right. Typically the version is project metadata, applied at compilation time via configuration; it is not part of the program proper.

2024-03-12 14:27 UTC, genivia-inc commented
> > Instead of [5.0.0] in configure.ac, I prefer to use the major and minor version only, which means less manual updating to do.
> > Instead of `PACKAGE_VERSION` in ugrep.hpp, I have to use the "5.1.1" string because I'm also building on MSVC++ without autotools.
> 
> So you **want** the version string in configure.ac to be different than that in visual studio? You don't care that the version number that source users see is different than the binary users?

No, that is not what I said. I want to keep a literal version string. The versions info in configure.ac doesn't matter (much) anyway in the project as it is not used anywhere, but perhaps for package maintainers it is important. Don't know.

The project should also compile without having to use or rely on autotools. That's what is more important.

2024-03-12 16:09 UTC, genivia-inc commented
Completion script generation can also be automated in makemake.sh, right after manual page generation:
~~~
./man.sh $1
pushd completions/fish ; ./compgen.sh > /dev/null ; popd || exit 1
pushd completions/zsh  ; ./compgen.sh > /dev/null ; popd || exit 1
~~~

2024-03-12 19:21 UTC, drok commented
> Note: renaming `compgen` to `compgen.sh` is preferable, so let's rename.

Renamed in eb1600b and 6ea3e86

2024-03-12 21:54 UTC, drok commented
> makemake.sh script for ugrep updating

This is a lot of work to avoid the built-in feature [`BUILT_SOURCES`](https://www.gnu.org/software/automake/manual/html_node/Sources.html) - you can have it generate a `version.h` as a built source (ie, distributed) which you add to git. This means you can use the version.h file in Visual Studio without having/depending on autotools there, while keeping the version number in sync with the AC_INIT source of truth.

The `makemake.sh` technique will definitely catch even experienced autotools users by surpise, as it doesn't fit the typical interface `autoreconf -i && ./configure && make && make install` - there is no step there for generating or patching a configure.ac file, and this hack is not described in any of the usual 'README' or 'INSTALL' files. I certainly had not noticed it until your message above, where you mention it.

Some programs that interact with your project absolutely use the version string in your AC_INIT. If you supply a version number, it should not be wrong, IMHO. I gave the example of the Autotools Integration extension for VSCode, which presents the version number, project name and issues URL from AC_INIT to users in the UI. The users will be understandably confused if VScode reports "ugrep 4.5" when they expected to see "ugrep 5.0.0"

2024-03-13 16:44 UTC, genivia-inc commented
> > makemake.sh script for ugrep updating
> 
> This is a lot of work to avoid the built-in feature [`BUILT_SOURCES`](https://www.gnu.org/software/automake/manual/html_node/Sources.html) - you can have it generate a `version.h` as a built source (ie, distributed) which you add to git. This means you can use the version.h file in Visual Studio without having/depending on autotools there, while keeping the version number in sync with the AC_INIT source of truth.

I do not use MSVC++ as my base development platform. Not sure when or how you inferred this from my comments.

I mostly use MacOS for development and also use Linux on several devices for projects and for testing portability and performance.
 
> The `makemake.sh` technique will definitely catch even experienced autotools users by surpise, as it doesn't fit the typical interface `autoreconf -i && ./configure && make && make install` - there is no step there for generating or patching a configure.ac file, and this hack is not described in any of the usual 'README' or 'INSTALL' files. I certainly had not noticed it until your message above, where you mention it.

Nobody should ever have to use `makemake.sh` besides me before a release. It's just doing things in sync that other folks typically do by hand. The fact that I include these scripts is a service to others interested in this and for completeness of the project repo. Otherwise, I will just strip the repo bare and others will have to figure out how to prep a release by hand instead.
 
> Some programs that interact with your project absolutely use the version string in your AC_INIT. If you supply a version number, it should not be wrong, IMHO. I gave the example of the Autotools Integration extension for VSCode, which presents the version number, project name and issues URL from AC_INIT to users in the UI. The users will be understandably confused if VScode reports "ugrep 4.5" when they expected to see "ugrep 5.0.0"

Again, I don't care 0% about VScode. Not using it. Neither should others. I've documented all the MSVC++ projects build stuff in [ugrep/vs](https://github.com/Genivia/ugrep/tree/master/vs) for you and anyone else to use, if need be.

2024-03-13 18:52 UTC, genivia-inc commented on include/reflex/absmatcher.h
This is wrong. When `HAVE_AVX512BW` is defined then you are disabling run-time test for AVX2 that can be used when the binary is moved to a non-AVX512BW machine. This breaks binary portability!

2024-03-13 18:59 UTC, genivia-inc commented on Makefile.am
This is the wrong approach. The 7zip code should be compiled as a "library" to include or not depending on the configure --disable-7zip switch. It is not and should NOT be compiled as part of the ugrep source code.

2024-03-13 20:13 UTC, genivia-inc commented
> > I prefer to use the major and minor version only, which means less manual updating to do.
> 
> Sorry I've been engaged in some other work and havn't had time to follow ever detail here.
> 
> On the versioning front though I'd like to suggest there is a better way to get both more detailed versioning AND require zero maintenance. I've implemented autotools hooks for versioning from Git that set the version string relative to release tags, usable without intervention from from either Git clones or source dist packages (`make dist`) (not `git archive` generated tarballs). No source files to edit, ever, and every source and binary build has either the exact tag release for releases or additional counter info for commits between releases.
> 
> You can see this working on projects like `vcsh`, `git-warp-time`, `sile`, and many more.
> 
> If no manual-updating at all sounds good I'll try to add a PR into this one.

I appreciate your involvement and suggestions.

That's very neat and good for you.

But personal use cases are not transferrable to others who might prefer different scenarios to work on projects and release updates. I am very well aware what others do.

I want to make sure it is always possible to have zero dependence on Git and zero dependence on autotools as a fallback. I learned my lessons in the past. Everything should be buildable, maintainable and updatable without requiring or using git and autotools. Use git and autotools only as support to release and install the project. This means I won't take a tag from git to update the version field. Likewise, I won't take the `AC_INIT` version field to expand in the code. The code base is the boss, not the environment that supports releasing and installing it.

2024-03-13 20:51 UTC, genivia-inc commented
https://github.com/Genivia/ugrep/pull/370/commits/ebe6400c7b19e92176539f0ba93f1a58397b5b64

Two problems with this.

The logic is wrong as I've pointed out i.e. `--with-bzip3` should check to link bzip3 explicitly. Bzip3 is not linked by default, unlike the other libs.

So I patched it like this:
~~~
AC_ARG_WITH(bzip3,
  [AS_HELP_STRING([--with-bzip3],
                  [Use the bzip3 library when installed to decompress .bz3 files])],
  [with_bzip3_library="$withval"],
  [with_bzip3_library=""])
AS_IF([test "x$with_bzip3_library" != "x"],[
  PKG_CHECK_MODULES([BZIP3], [libbzip3],
    [AC_DEFINE([HAVE_LIBBZIP3], [1], [Use libbzip3 compression library])
    CXXFLAGS="$CXXFLAGS $BZIP3_CFLAGS"
    LIBS="$LIBS $BZIP3_LIBS"
    ],
    # libbzip3 is optional by default, but required if --enable-bzip3 is given
    [AS_IF([test -z "$enable_bzip3" ],
      [AC_MSG_WARN([libbzip3 not found (optional): ugrep option -z cannot search .bz3 files])],
      [AC_MSG_ERROR([libbzip3 not found. Is the devel package installed?])],
    )]
  )
])
~~~
But this `PKG_CHECK_MODULES` fails to detect bzip3:
~~~
checking for libbzip3... no
configure: WARNING: libbzip3 not found (optional): ugrep option -z cannot search .bz3 files
~~~
when it worked before:
~~~
checking if bzip3 is wanted... yes
checking for bz3_new in -lbzip3... yes
checking for libbz3.h... yes
~~~
Also, note that I really like to do this for all libraries that are not required, so I do not need to pollute the Makefile.am with these `XYZ_LIBS` all over the place:
~~~
    CXXFLAGS="$CXXFLAGS $BZIP3_CFLAGS"
    LIBS="$LIBS $BZIP3_LIBS"
~~~
Perhaps `CPPFLAGS` might be OK too. Just drafting something up here.

2024-03-13 21:24 UTC, genivia-inc commented
https://github.com/Genivia/ugrep/pull/370/commits/6978c50c0d60226a076ea1ff78ea4d34ed1be1c4

This is incomplete. We can't disable pcre2 this way and try boost.

To do this properly:
~~~
AC_ARG_ENABLE([pcre2],[
  --enable-pcre2          Use PCRE2 for option -P
                          @<:@defaults to enabled if PCRE2 is installed@:>@
  --disable-pcre2         Do not use PCRE2])
AS_IF([test "$enable_pcre2" != "no"],[
  PKG_CHECK_MODULES([PCRE2], [libpcre2-8],
    [AC_DEFINE([HAVE_PCRE2], [1], [Use PCRE2 (Perl Compatible Regular Expression Library)])
     have_pcre2=yes
     CXXFLAGS="$CXXFLAGS $PCRE2_CFLAGS"
     LIBS="$LIBS $PCRE2_LIBS"
    ],
    [AC_MSG_RESULT(no)]
  )
])

if test "${have_pcre2}" != "yes" ; then

# Check for libboost-regex library and header, adds
AC_SEARCH_LIBS([regcompA], [boost_regex boost_regex-mt], [
  # Check for boost regex header
  AC_CHECK_HEADER([boost/regex.hpp], [
    BOOST_REGEX_FOUND=true
    AC_DEFINE([HAVE_BOOST_REGEX], [1], [Use Boost Regex library])
    AC_DEFINE([BOOST_REGEX_STANDALONE], [1], [Signal to boost lib that it is being used without the rest of boost])
  ],
  [AC_MSG_WARN([PCRE2 not found and Boost Regex.hpp not found])
  ])
],
[AC_MSG_WARN([PCRE2 not found and Boost Regex.hpp not found])
])

fi
~~~

2024-03-13 21:27 UTC, genivia-inc commented
https://github.com/Genivia/ugrep/pull/370/commits/2fd7710e88caf164acb99f4ed119236bae87b74c

There is a mistake. The `have_libz=yes` var is set, but not used in the test below it. It libz is not available, then none of the other compression libraries should be linked. They all become defunct.

The test below it should be:
~~~
if test "${have_libz}" = "yes" ; then
~~~

2024-03-13 21:37 UTC, genivia-inc commented
https://github.com/Genivia/ugrep/pull/370/commits/8a4797188d2013252f0bfca11c49875ed079e270
https://github.com/Genivia/ugrep/pull/370/commits/9423c6bf1047d99906b5eea975ffb0e81a2c0ccc

These suggested changes do not produce checking ... and then report no with a note the the library is **recommended**. I really like to see a note with recommended here.

https://github.com/Genivia/ugrep/pull/370/commits/a27012a08a452fcd49fc82215ed10874ebf65350
https://github.com/Genivia/ugrep/pull/370/commits/4d2b26d838184ed33bbea37d4e3ce34d7c373e3b
https://github.com/Genivia/ugrep/pull/370/commits/b596048a4c7ff75e98f1a074655fc11874e0ada4

These suggested changes do not produce checking ... and then report no with a note the the library is **optional**. I really like to see a note with the checking result.

I will make the changes on my end if this is too much work. I've already done most of the work the last hour or so while verifying the PR. I see too many problems so far and I've explained why.

2024-03-14 02:04 UTC, genivia-inc commented
The decision to use `PKG_CHECK_MODULES` is questionable:
https://stackoverflow.com/questions/10220946/pkg-check-modules-considered-harmful

Can you explain why you believe it is superior to `AC_CHECK_LIB` like the ones in the m4 files in ugrep/m4?

2024-03-14 17:04 UTC, drok commented
> These suggested changes do not produce checking ... and then report no with a note the the library is **recommended**. I really like to see a note with recommended here.

IMHO, recommendations belong in a place that humans read, and there is a designated place to document such things. See https://www.gnu.org/prep/standards/standards.html#Releases

I have pointed out the need for an INSTALL file several times already.

The output of the configure command is not commonly read by people, unless diagnosing/debugging (ie, when something has already gone wrong). It's not where people expect to find installation documentation.

People typically expect to find information and explanations in README, INSTALL, RELEASE-NOTES.txt and other such files written by another person. Not everyone reads documentation, but those who do expect to find it where documentation is supposed to go.

I should mention that when/if you decide that any of this PR is useful, you don't have to take the proposals as-is; you can edit your merge before committing, and in that edit you can choose to keep any, all or none of the proposed changes. What you keep and what you don't is at your discretion, you don't need to convince me to change my proposal.

My proposal reflects what I believe is the best uninterested advice I can give you, and that is the only advice I intend to give you. I don't intend to give you any less than my best advice. I have taken your feedback into consideration and will continue to do so, and amend my proposal where I made a mistake. You've already pointed out a few genuine mistakes, for which I am grateful, and I have fixed my proposal with "!fixup" commits.

However, where your feedback lacks merit, or where it's based on personal preference rather than reason, and where your preference conflicts with documented best practices or my experience, you cannot reasonably expect that I adopt your preference as my best advice. I have adopted your preference in places where it doesn't conflict with best practices (eg, renaming compgen to compgen.sh) or lessens the quality of my work.

That being said, I would like to reiterate, what I give you is merely a proposal, and you are entitled to reject it in its entirety, accept it in its entirety, or accept any part of it that you like at your own discretion.

2024-03-14 18:11 UTC, drok commented
> The decision to use `PKG_CHECK_MODULES` is questionable: https://stackoverflow.com/questions/10220946/pkg-check-modules-considered-harmful
> 
> Can you explain why you believe it is superior to `AC_CHECK_LIB` like the ones in the m4 files in ugrep/m4?

My pleasure.

The .pc file published by library maintainers/authors contains information about compilation requirements of the library such preprocessor options (includedir), compiler options (cflags), optimization options, linker options, as well as a list of -l &lt;library&gt; options to be used at link time (eg, see openssl library: `pkg-config --libs openssl` recommends _LIBS contain `-lssl -lcrypto`). This allows the authors to change their dependencies or optimizations from one release to the next, as they see fit; their compile specifications travel with the library, and are consistent with each other.

The AC_CHECK_LIB method is not capable of inferring optimization flags or additional dependencies. With that method, the list of compile flags and dependencies must be known _a priori_ by the coder who writes down the AC_CHECK_LIB check.

Some libraries do not come with pkg-config files (ie, the author has not communicated any compile time requirements, or even a name by which their library should be known; eg, the boost authors' choice of library name, 'boost_regex-mt' was not adopted by the Debian maintainers, and thus the library is named `boost_regex` in their distro). In those cases, library users (other developers who want the functionality), must guess the library name, compile flags and extra dependencies. Guessing means that some of the time, on some distros, the guess is wrong.

Case in point: the OpenSSL project publishes a .pc file. Their project name is `openssl` on every distro. That is the name you can use to reliably find the pc file, anywhere. The openssl "package" does not contain any libraries, but depends on two other packages, "libssl" and "libcrypto" - the fact that these package names are the same as the library names they contain is half coincidence, half creativity. The packages "libssl" also depends on the package "libcrypto". In turn, each of these packages includes a .pc file which lists the library name to be added to the linker command line. It is a library name that distro maintainers can change to anything they please; it can be reliably found with `pkg-config openssl` on every distro that includes openssl. The name 'openssl' is invariant, while the library name is arbitrary, although it doesn't usually vary.

Library authors who do publish a .pc file have the ability to pick a package name (not to be confused with library name) by which their lib will be known, and which is highly likely to be adopted by distro maintainers, unless it conflicts with another lib. They also can communicate ABI, optimizations, and other compile-time and link-time options to their users, as well as retain the ability to change these flags as they see necessary in the future, with the knowledge that their changes will propagate reliably through the supply chain to their users.

AC_CHECK_LIB don't have a supply chain to propagate flags through. The library author that relies on the users using AC_CHECK_LIB are limited to using only well-known flags (ie, none) and extra dependencies (none), and don't have the freedom to change them in future versions, lest they break existing detection scripts.

pkg-config implements disciplined propagation of metadata, while AC_CHECK_LIB implements guessing.

Turning to the [stackoverflow question](https://stackoverflow.com/questions/10220946/pkg-check-modules-considered-harmful) - the question itself contains a very good use case - the GTK library with an intricate set of dependencies. The pkg-config file reliably finds a complete, correct list of dependencies, while an AC_CHECK_LIB equivalent would be a smorgasbord of guesses.

The accepted answer is poorly reasoned because:
1. It gives an theoretical example where a library is installed in a non-standard location `/p/a/t/h` and then expects that pkg-config should be able to find it without setting `PKG_CONFIG_PATH` - it does not explain how pkg-config can be expected to know the non-standard path the user chose. There is no magic in the process, but the answer giver seems to expect that some magic will occur that makes in unnecessary to set `PKG_CONFIG_PATH`
2. The answer giver believes that pkg-config reads the variable `LDFLAGS` and is able to make inferences from it. He says that running configure with `LDFLAGS=-L/p/a/t/h` should tell pkg-config that a .pc file can be found at /p/a/t/h - this demonstrates a fundamental lack of understanding of the purpose of LDFLAGS, and the fact that library files (*.so) aren't typically, nor do they need to be installed in the same location as package manifest files (*.pc). For greater certainty, LDFLAGS is meant to provide linker customizations (see `ld --help`), while -L/p/a/t/h together with library name, is a specification of what the input is, rather than how linking should be done (ie, inputs are not the same as options)
3. In his edit, he states `The autotools are not a package management system` which is true, but he seems to believe that pkg-config is part of autotools, and it is not. pkg-config is a separate program that happens to be commonly used with autoconf, just as a C compiler, awk, and sed and sh are commonly used with autoconf. In fact, the autoconf program does depend on pkg-config. They do happen to both be classified as 'developer tools', and thus distros typically install them together. This does not make autotools a package management system, just as it doesn't make them a compiler, a stream editor/text processor, or a shell management system.

The accepted answer is opinionated and shows misconceptions about the ecosystem. In this case, his opinions seem plausible to someone who is uninformed, and thus he has a number of 'followers', but it would not pass the scrutiny of someone who is informed, as some of the commenters.

2024-03-14 18:27 UTC, genivia-inc commented
> The output of the configure command is not commonly read by people, unless diagnosing/debugging (ie, when something has already gone wrong). It's not where people expect to find installation documentation.

I agree from a package maintainer's point of view. But when manually installing the package and to develop and maintain the software now and in the future by me or anyone who isn't just interested in unpacking and installing the software, these messages we get from configure are useful. Otherwise, what's the point of configure to produce messages? Real warnings and errors should be distinguishable from checking notes, i.e. `AC_MSG_NOTICE` for a note that something entirely optional is not included makes sense I would think (which is silenced when need be) versus `AC_MSG_WARN` when a recommended component is not included versus `AC_MSG_ERROR` when a component is missing. There is a preferential difference in the usage of libraries by ugrep.

> However, where your feedback lacks merit, or where it's based on personal preference rather than reason, and where your preference conflicts with documented best practices or my experience, you cannot reasonably expect that I adopt your preference as my best advice. I have adopted your preference in places where it doesn't conflict with best practices (eg, renaming compgen to compgen.sh) or lessens the quality of my work.

I have no personal preferences wrt. to autotools. But changes in the logic that change the original logic flow and result need correcting, whether these changes are in scripts or in the C++ code base. Changes to improve the C++ code base can be opened separately as issues when there is a potential problem, but not be part of a PR to overhaul autotool use. It also makes it much harder to review the PR.

Perhaps things in the PR may make your life easier, but not all changes are a win-win. For example, using makefiles for static data (man page, compgen, patterns) makes my work miserable having to juggle more moving parts in the project. The 7 points lay that out. More moving parts and dependent stuff spread out across Makefiles increases fragility.

So I wonder why `PKG_CHECK_MODULES` is controversial (well, at least a couple of years ago). It is also not consistently used in your PR, where in some cases `AC_SEARCH_LIBS` is also used. If `AC_SEARCH_LIBS` is safer bet (or`AC_CHECK_LIB` perhaps), then we should go with that, no?

2024-03-14 21:39 UTC, drok commented
> It is also not consistently used in your PR, where in some cases `AC_SEARCH_LIBS` is also used. If `AC_SEARCH_LIBS` is safer bet (or`AC_CHECK_LIB` perhaps), then we should go with that, no?
> 
> NOTE: this was cross-posted with the post above that I did not see, which answers part of these questions.

My post on the topic of `PKG_CHECK_MODULES` addresses part of the questions, as you note, but for greater certainty, let me directly answer your question on why `PKG_CHECK_MODULES` is not used consistently.

As I mentioned in the `PKG_CHECK_MODULES` response, some packages do not provide a .pc file, so it is not possible to use PKG_CHECK_MODULES with them. The following of your dependencies fall in this category (these are **library names**):

  - boost_regex/boost_regex-mt
  - bz2

The other dependencies do supply a .pc file, so PKG_CHECK_MODULES is used to discover their coordinates (these are **package names**):
  - libpcre2-8
  - zlib
  - liblzma
  - liblz4
  - libzstd
  - libbrotlidec

The choice to use PKG_CHECK_MODULES or AC_SEARCH_LIBS was not discretionary, but was dictated by whether the respective software is distributed with a .pc manifest file or not.

2024-03-14 22:08 UTC, genivia-inc commented
https://github.com/Genivia/ugrep/pull/370/commits/b4ba7e5ec0cace0c40bc7437f447ff56a0ec6366

This does not appear to detect NEON on MacOS M1.
~~~
test "x$ax_cv_support_neon_ext" = "xyes"
~~~
is false. Looking into `ax_ext.m4`, there are `arm)` and `aarch64)` arms that differ where `arm)` sets `ax_cv_support_...` but `aarch64)` does not, which is where MacOS "lives".

2024-03-15 00:47 UTC, drok commented
> is false. Looking into `ax_ext.m4`, there are `arm)` and `aarch64)` arms that differ where `arm)` sets `ax_cv_support_...` but `aarch64)` does not, which is where MacOS "lives".

You're right. My apologies for the mistake. Fixed in df64e49

2024-03-15 00:48 UTC, genivia-inc commented
You've not included this new line for `aarch64)`
~~~
eval ax_cv_support_${ac_instr_acvar}_ext=yes
~~~
However, now when NEON is detected on MacOS, an old friend warning pops up that I squashed in the past in my config code:
~~~
clang: warning: argument unused during compilation: '-mfpu=neon' [-Wunused-command-line-argument]
~~~
That's why the NEON detection in my code has three different stages to include or not certain flags, in the case of MacOS it detects that `-DHAVE_NEON` suffices which simply enables the NEON supported intrinsics in ugrep.

2024-03-15 01:02 UTC, genivia-inc commented
To experiment a bit around with this `ax_ext.m4` stuff, I'm using the following which I've adapted from your PR, without having to change anything to my makefiles and code base:
~~~
AC_ARG_ENABLE(simd,
[AS_HELP_STRING([--disable-simd],
                [disable SIMD CPU extensions (SSE2, AVX, NEON, etc)])],
[with_no_simd="yes"],
[with_no_simd="no"])
if ! test "$with_no_simd" = "yes"; then

  # Temporarily set cross_compiling mode to detect if the compiler supports
  # AVX2 / AVX512 but not check the compiling CPU
  save_cross_compiling=$cross_compiling
  cross_compiling=yes

  # Tell AX_EXT that the CPU supports it, because runtime will check.
  ax_cv_have_avx2_cpu_ext=yes
  ax_cv_have_avx512bw_cpu_ext=yes
  ax_cv_have_sse2_cpu_ext=yes

  ax_cv_have_avx2_ext=yes
  ax_cv_have_avx512bw_ext=yes
  ax_cv_have_sse2_ext=yes
  ax_cv_have_neon_ext=yes

  AX_EXT
  cross_compiling=$save_cross_compiling

fi

if test "$ax_cv_support_sse2_ext" = "yes"; then
  if test "$ax_cv_support_avx2_ext" = "yes"; then
    if test "$ax_cv_support_avx512bw_ext" = "yes"; then
      SIMD_FLAGS="-msse2 -DHAVE_AVX512BW"
      SIMD_AVX2_FLAGS="-mavx2"
      SIMD_AVX512BW_FLAGS="-mavx512bw"
    else
      SIMD_FLAGS="-msse2 -DHAVE_AVX2"
      SIMD_AVX2_FLAGS="-mavx2"
    fi
  else
    SIMD_FLAGS="-msse2 -DHAVE_SSE2"
  fi
else
  if test "$ax_cv_support_neon_ext" = "yes"; then
    # FIXME does not work on MacOS that we know rejects -mfpu=neon that e.g. ARM7 needs
    SIMD_FLAGS="-mfpu=neon -DHAVE_NEON"
  fi
fi
~~~
Note that `SIMD_FLAGS="-msse2 -DHAVE_SSE2"` is what I want when SSE2 is detected, i.e. all code is compiled with `-msse2` and intrinsics are compiled by setting `-DHAVE_SSE2`. That is the gist of it.

2024-03-15 17:12 UTC, genivia-inc commented
It looks like using CPUID alone in `ax_ext.m4` to detect SIMD extensions does not work as advertised.

Furthermore, using CPUID alone is also incomplete, because the compiler may not support SIMD intrinsics. In that case the build will fail. It could fail because of a missing header file, such as `immintrin.h` for example.

By contrast, compiling and running a short program that tests the presence and execution of SIMD intrinsics is more robust. That's one reason why I wrote these checks in the first place.

I will investigate and experiment a bit more for the 7 point battle plan, in particular points 6 and 7. I may end up rewriting part of my own code with solutions that actually work.

2024-03-15 21:06 UTC, genivia-inc commented
Updating configure.ac is done, except for cross compilation checks (see below).

Everything is working and verified.

NEON is now accurately detected and compiles properly on ARM6 (no NEON), ARM7 and Android ARM-A72, MacOS M1. The checks perform compile-time checks (without  the dreaded `-march=native`) and also runtime execution checks.

Now also the SSE2/AVX2/AVX512BW checking is performed without  the dreaded `-march=native` using a compile-time and runtime check.

The external m4's are reduced to these four, by using `PKG_CHECK_MODULES` when possible:
ax_boost_regex.m4
ax_check_bzip3lib.m4
ax_cxx_compile_stdcxx_11.m4
ax_pthread.m4

I recommend to remove the failing `ax_ext.m4` and `ax_gcc_` files. These are useless and do not work as documented.

Last step is to handle cross compilation:

> I don't know how folks and package maintainers invoke `./configure` to cross-compile binaries that benefit from SIMD CPU extensions. Turning all SIMD CPU extensions off is really bad and unnecessary. Therefore, enabling them is important.
> 
> We should check for `$cross_compiling`. I assume that when cross-compiling, configure should be run with e.g. `--enable-sse2` or `--enable-neon` to enable the corresponding SIMD CPU extensions?

Any suggestions? This is what I want to do:
~~~
if ! test "$with_no_simd" = "yes"; then

  if test "x$cross_compiling" = "xyes"; then

    # FIXME should we listen to --enable-sse2 / --enable-avx2 / --enable-avx512bw / --enable-neon ???
    AC_MSG_WARN([cross compiling])

  else
     ... the current SSE2/AVX2/AVX512BW checking ...
~~~

2024-03-16 02:35 UTC, genivia-inc commented
Ah. I figure it out for the missing part to handle cross compilation to detect SIMD CPU extensions. It's rather trivial. Tested and verified with ARM6, ARM7 and AArch64 devices and an Intel CPU.
~~~
if test "x$cross_compiling" = "xyes"; then

    # cross compiling to a host CPU, check support for SIMD CPU extension compile flags
    case $host_cpu in
      i[[3456]]86*|x86_64*|amd64*)
        AX_CHECK_COMPILE_FLAG([-msse2],
                              [msse2_ok=yes],
                              [msse2_ok=no])
        if test "x$msse2_ok" = "xyes"; then
          AX_CHECK_COMPILE_FLAG([-mavx2],
                                [mavx2_ok=yes],
                                [mavx2_ok=no])
          if test "x$mavx2_ok" = "xyes"; then
            AX_CHECK_COMPILE_FLAG([-mavx512bw],
                                  [mavx512bw_ok=yes],
                                  [mavx512bw_ok=no])
            if test "x$mavx512bw_ok" = "xyes"; then
              SIMD_FLAGS="-msse2 -DHAVE_AVX512BW"
              SIMD_AVX2_FLAGS="-mavx2"
              SIMD_AVX512BW_FLAGS="-mavx512bw"
            else
              SIMD_FLAGS="-msse2 -DHAVE_AVX2"
              SIMD_AVX2_FLAGS="-mavx2"
            fi
          else
            SIMD_FLAGS="-msse2 -DHAVE_SSE2"
          fi
        fi
      ;;
      armv5*|armv6*)
      ;;
      arm*)
        AX_CHECK_COMPILE_FLAG([-mfpu=neon],
                              [SIMD_FLAGS="-mfpu=neon -DHAVE_NEON"],
                              [SIMD_FLAGS=""])
      ;;
      aarch64*)
        SIMD_FLAGS="-DHAVE_NEON"
      ;;
    esac
~~~
Note that we expect x86/x64 machines to support SSE2, which is reasonable. Also note that we compile all the way up to AVX2 and AVX512BW, which will be selected at runtime based on CPUID of the machine on which ugrep runs.

I wonder what `ax_ext.m4` is trying to do with `arm)`. It's clearly wrong, because `arm)` will not match specific ARM hosts and we cannot even distinguish ARM6 from ARM7 with ARM7 supporting NEON. The `ax_ext.m4` is trash IMO.

2024-03-18 01:19 UTC, genivia-inc commented
Found a problem with Boost Regex check a couple of days ago, but didn't report it.

When using Boost Regex installed with Homebrew on MacOS in `/opt/homebrew/lib/libboost_regex-mt.{a,dylib}` which is the default path of Brew, this code will not find it:
~~~
        # Check for libboost-regex library and header, adds
        AC_SEARCH_LIBS([regcompA], [boost_regex boost_regex-mt], [
          # Check for boost regex header
          AC_CHECK_HEADER([boost/regex.hpp], [
            BOOST_REGEX_FOUND=true
            AC_DEFINE([HAVE_BOOST_REGEX], [1], [Use Boost Regex library])
            AC_DEFINE([BOOST_REGEX_STANDALONE], [1], [Signal to boost lib that it's being without the rest of boost])
          ]
~~~
but this does:
~~~
if test "x$have_pcre2" != "xyes"; then
  # PCRE2 was not found: check for alternative Boost Regex library and header
  AX_BOOST_REGEX
  AC_DEFINE([BOOST_REGEX_STANDALONE],[1],[Signal to boost lib that it is being used without the rest of boost])
fi
~~~
where `AX_BOOST_REGEX` is defined in `ax_boost_regex.m4`.

2024-04-03 20:29 UTC, closed without merging